alias al_edit_bash="sudo vim ~/.bash_profile"
alias al_view_pub="sudo cat ~/.ssh/id_rsa.pub"
alias al_view_rsa="sudo cat ~/.ssh/id_rsa"

alias al_cmd_apache_start="sudo apachectl -k restart"
alias al_cmd_apache_stop="sudo apachectl stop"
alias al_cmd_memcache_start="sudo memcached -d -c 1024 -m 1024 -u root"
alias al_cmd_memcache_check="echo stats | nc localhost 11211 | grep pid "
alias al_cmd_memcache_restart="sudo service memcached restart"

alias al_cmd_git_submodule="git submodule update -i"
alias al_cmd_checktcp='netstat -n | awk '"'"'/^tcp/ { S[$NF]} END {for ( a in S ) print a, S[a]}'"'"''
alias al_cmd_checkhttpd="ps -ef | grep httpd | wc -l"

alias ga="git add "
alias gc="git checkout "
alias gd="git diff --ignore-space-at-eol -w "
alias gs="git status "
alias gl="git log "
alias gm="git commit -m "
alias gp="git pull "
alias go="git push origin "

alias pt="python -m cProfile "

alias mysql=/usr/local/mysql/bin/mysql
alias mysql_login="/usr/local/mysql/bin/mysql -u root -p ''"

alias vi=vim
alias ls="ls -hG"
alias la="ls -FGa"
alias ll="ls -FGls"
